# Site settings
title: dumbblog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dumbblog"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ['README.md', '_site']
paginate: 1 # this is just for an example

#2016-08-21 following http://jekyll-windows.juthilo.com/3-syntax-highlighting/

#highlighter: pygments 

gems: [jekyll-paginate] 

encoding: utf-8 

#highlighter error
#  Dependency Error: Yikes! It looks like you don't have pygments or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
#  Liquid Exception: pygments in C:/Users/Donagh/Documents/0_MyFolders/Computers_General/Git_Xiddler_Website/dumbblog/_posts/2015-07-22-getting-better-looking-each-day.md
#             ERROR: YOUR SITE COULD NOT BE BUILT:
#                    ------------------------------------
#                    pygments

